# Generated by Django 3.2.8 on 2021-10-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211017_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'المستخدمين', 'verbose_name_plural': 'المستخدمين'},
        ),
    ]
