# Generated by Django 3.2.8 on 2021-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('nationality', models.CharField(max_length=150, verbose_name='الجنسية')),
                ('qid', models.CharField(max_length=150, verbose_name='QID')),
                ('qid_expiration_date', models.DateField(null=True, verbose_name=' تاريخ انتهاء QID')),
                ('passport_number', models.CharField(max_length=10, null=True, verbose_name='رقم الجواز')),
                ('expiration_date', models.DateField(null=True, verbose_name=' تاريخ انتهاء الجواز')),
                ('guarantee', models.CharField(max_length=150, verbose_name='الكفالة')),
                ('settlement_id', models.CharField(max_length=150, verbose_name='اي دي الاقامة')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='الراتب الاساسي')),
                ('feeding_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='بدل غذاء')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='بدل سكن')),
                ('transporting_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='بدل انتقال')),
            ],
            options={
                'verbose_name': 'العمال',
                'verbose_name_plural': 'العمال',
            },
        ),
    ]
