# Generated by Django 3.2.8 on 2021-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='الاسم'),
        ),
    ]
