# Generated by Django 3.2.8 on 2021-10-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_worker_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'الادارة', 'verbose_name_plural': 'الادارة'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='feeding_allowance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='housing_allowance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transporting_allowance',
        ),
    ]
