# Generated by Django 3.2.8 on 2021-11-18 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211023_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='settlement_id',
        ),
        migrations.AddField(
            model_name='worker',
            name='start_working_date',
            field=models.DateField(null=True, verbose_name=' تاريخ مباشرة العمل '),
        ),
        migrations.AlterField(
            model_name='worker',
            name='qid',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[0-9]{9}', 'مطلوب عشر ارقام صجيجة قثط')], verbose_name='QID'),
        ),
    ]
