# Generated by Django 3.2.8 on 2021-11-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0010_alter_vacations_worker'),
        ('accounts', '0013_auto_20211118_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affairs.activity'),
        ),
    ]
