# Generated by Django 3.2.8 on 2021-10-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_auto_20211015_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affairs.activity', verbose_name='اسم النشاط'),
        ),
    ]
