# Generated by Django 3.2.8 on 2021-10-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affairs', '0005_alter_day_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('start_date', models.DateField(verbose_name='بداية من')),
                ('end_date', models.DateField(verbose_name='نهاية الي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
        ),
    ]
