# Generated by Django 3.2.8 on 2021-10-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0006_vacations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacations',
            options={'verbose_name': 'الاجازات', 'verbose_name_plural': 'الاجازات'},
        ),
    ]
